# @name listCategory
GET http://127.0.0.1:8000/blogCategories
###

# @name readCategory
GET http://127.0.0.1:8000/blogCategories/
###

# @name postCategory
POST  http://127.0.0.1:8000/blogCategories
Content-Type: application/json

{
  "name": "title-1"
}
###

# @name updateCategory
PUT  http://127.0.0.1:8000/blogCategories/
Content-Type: application/json

{
  "name": "title-7"
}
###

# @name deleteCategory
DELETE  http://127.0.0.1:8000/blogCategories/
Content-Type: application/json
###

# @name listBlogPosts
GET http://127.0.0.1:8000/blogPosts
###

# @name readBlogPost
GET http://127.0.0.1:8000/blogPosts/
###

# @name postBlogPost
POST  http://127.0.0.1:8000/blogPosts
Content-Type: application/json

{
  "title": "title-1",
  "content":"Content for post 1",
  "categoryId":"69aeb6e6e889be6307d0c4d9"
}
###

# @name updateBlogPost
PUT  http://127.0.0.1:8000/blogPosts/
Content-Type: application/json

{
  "title": "title-115",
  "content":"Content for post 2",
  "categoryId":"69aeb6e6e889be6307d0c4d9"
}
###

# @name deleteBlogPost

DELETE  http://127.0.0.1:8000/blogPosts/
Content-Type: application/json

###

# @name listUsers
GET http://127.0.0.1:8000/users/
###

# @name readUsers
GET http://127.0.0.1:8000/users/
###

# @name createUser
POST  http://127.0.0.1:8000/users
Content-Type: application/json

{
  "email": "user-1@gmail.com",
  "password":"1234567890",
  "userName":"user - 1",
  "firstName":"user - cx ",
  "lastName":"user - cx "
}
###

# @name updateUsers
PUT  http://127.0.0.1:8000/users/
Content-Type: application/json

{
  "email": "kullanici1@gmailcom",
  "password":"123456789",
  "userName":"kullanici1",
  "firstName":"kullanici1",
  "lastName":"kullanici1"
}
###

# @name deleteUsers
DELETE  http://127.0.0.1:8000/
Content-Type: application/json

###
# @name Login
POST   http://127.0.0.1:8000/users/login
Content-Type: application/json

{
  "email": "user-1@gmail.com",
  "password":"1234567890"

}
###
# @name logout
POST   http://127.0.0.1:8000/users/logout
Content-Type: application/json

{
  "email": "user-1@gmail.com",
  "password":"1234567890"

}
###